=== code-blessing/sourceamazing/documentation/html-form-example/input-data/schema/sourceamazing-xml-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="https://codeblessing.org/sourceamazing/sourceamazing-xml-schema" elementFormDefault="qualified" targetNamespace="https://codeblessing.org/sourceamazing/sourceamazing-xml-schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- - - - - - - - -       CONCEPT IDENTIFIER ATTRIBUTE     - - - - - - - -->
    <xsd:attributeGroup name="conceptIdentifier">
        <xsd:attribute name="conceptIdentifier" type="xsd:ID"/>
    </xsd:attributeGroup>
    <!-- - - - - - - - -       CONFIGURATION AND DEFINITIONS     - - - - - - - -->
    <xsd:element name="sourceamazing">
        <xsd:complexType>
            <xsd:sequence maxOccurs="1" minOccurs="1">
                <xsd:element name="definitions">
                    <xsd:complexType>
                        <!-- - - - - - - - -       ROOT CONCEPTS     - - - - - - - -->
                        <xsd:choice maxOccurs="unbounded" minOccurs="0">
                            <xsd:element name="htmlPage" type="htmlPageType"/>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- - - - - - - - -       ALL CONCEPTS AS TYPES     - - - - - - - -->
    <xsd:complexType name="htmlPageType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="htmlPageSection" type="htmlPageSectionType"/>
        </xsd:choice>
        <xsd:attributeGroup ref="conceptIdentifier"/>
        <xsd:attributeGroup ref="htmlPagePageTitleName"/>
    </xsd:complexType>
    <xsd:complexType name="htmlPageSectionType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0">
            <xsd:element name="htmlInputField" type="htmlInputFieldType"/>
        </xsd:choice>
        <xsd:attributeGroup ref="conceptIdentifier"/>
        <xsd:attributeGroup ref="htmlPageSectionSectionName"/>
    </xsd:complexType>
    <xsd:complexType name="htmlInputFieldType">
        <xsd:choice maxOccurs="unbounded" minOccurs="0"/>
        <xsd:attributeGroup ref="conceptIdentifier"/>
        <xsd:attributeGroup ref="htmlInputFieldFieldName"/>
        <xsd:attributeGroup ref="htmlInputFieldRequired"/>
        <xsd:attributeGroup ref="htmlInputFieldMaxFieldLength"/>
    </xsd:complexType>
    <!-- - - - - - - - -       ALL ATTRIBUTES      - - - - - - - -->
    <xsd:attributeGroup name="htmlPagePageTitleName">
        <xsd:attribute name="pageTitleName" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="htmlPageSectionSectionName">
        <xsd:attribute name="sectionName" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="htmlInputFieldFieldName">
        <xsd:attribute name="fieldName" type="xsd:string"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="htmlInputFieldRequired">
        <xsd:attribute name="required" type="xsd:boolean"/>
    </xsd:attributeGroup>
    <xsd:attributeGroup name="htmlInputFieldMaxFieldLength">
        <xsd:attribute name="maxFieldLength" type="xsd:integer"/>
    </xsd:attributeGroup>
</xsd:schema>

=== code-blessing/sourceamazing/documentation/html-form-example/input-data/input-data.xml
<?xml version="1.0" encoding="utf-8" ?>
<sourceamazing xmlns="https://codeblessing.org/sourceamazing/sourceamazing-xml-schema"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://codeblessing.org/sourceamazing/sourceamazing-xml-schema ./schema/sourceamazing-xml-schema.xsd">
    <definitions>
        <htmlPage pageTitleName="Person">
            <htmlPageSection sectionName="Names">
                <htmlInputField fieldName="Firstname" required="true" maxFieldLength="40" />
                <htmlInputField fieldName="Lastname" required="true" maxFieldLength="50" />
            </htmlPageSection>
            <htmlPageSection sectionName="Address">
                <htmlInputField fieldName="Street" required="false" maxFieldLength="60" />
                <htmlInputField fieldName="Zip" required="true" maxFieldLength="15" />
                <htmlInputField fieldName="Town" required="true" maxFieldLength="40" />
                <htmlInputField fieldName="Country" required="true" maxFieldLength="40" />
            </htmlPageSection>
        </htmlPage>
        <htmlPage pageTitleName="Company">
            <htmlPageSection sectionName="Company Information">
                <htmlInputField fieldName="Company Name" required="true" maxFieldLength="200" />
                <htmlInputField fieldName="Company Main Country" required="true" maxFieldLength="40" />
            </htmlPageSection>
        </htmlPage>
    </definitions>
</sourceamazing>
